# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/contourselectiontool
# Target is a library:  

INSTALLS += target 
target.path = /plugins/ 
HEADERS += contourselection.h
SOURCES += contourselection.cpp
KDEV_QTVER = 4
include(../tools_config.pri)
include(../../../../ktconfig.pri)
CONFIG += plugin
TEMPLATE = lib
