# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export
# Target is a subdirs project 

SUBDIRS += ffmpegplugin \
           genericexportplugin \
           mingplugin \
           smilexportplugin 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
