# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export
# Target is a subdirs project 

SUBDIRS += genericexportplugin \
           smilexportplugin 

contains(DEFINES, HAVE_FFMPEG) {
	SUBDIRS += ffmpegplugin
}

contains(DEFINES, HAVE_MING) {
	SUBDIRS += mingplugin
}

CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
