# File generated by kdevelop's qmake manager . 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/kom
# Target is a subdirs project 

SUBDIRS += kcore ksound kgui plugins
CONFIG += release \
warn_on
TEMPLATE = subdirs

