# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += lib \
           packages \
           modules \
           shell
CONFIG += warn_on \
thread \
qt
TARGET = ../bin/ktadmin
QT += gui
TEMPLATE = subdirs
