# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export/genericexportplugin
# Target is a library:  

QT += xml 
INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
include(../export.pri)

CONFIG += release \
          warn_on \
          plugin 
TEMPLATE = lib 
HEADERS += genericexportplugin.h 
SOURCES += genericexportplugin.cpp
