# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export/genericexportplugin
# Target is a library:  

INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
include(../export_config.pri)

CONFIG += plugin 
include(../../../../ktconfig.pri)
TEMPLATE = lib 
HEADERS += genericexportplugin.h 
SOURCES += genericexportplugin.cpp
