# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/ktoonstyle
# Target is a library:  

HEADERS += ktoonstyle.h 
SOURCES += ktoonstyle.cpp 
RESOURCES += ktoonstyle.qrc
KDEV_QTVER = 4
MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
