# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/export
# Target is a subdirs project 

SUBDIRS += ffmpegplugin \
           mingplugin \
           ui 
KDEV_QTVER = 4
INCLUDEPATH += ../../../src/store \
../../../src/lib
CONFIG += release \
warn_on
TEMPLATE = subdirs
