# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dsound/player
# Target is a library:  

INSTALLS += target 
target.path = /lib/ 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          dll 
VERSION = 0.0.1 
TEMPLATE = lib 
HEADERS += daudioengineiface.h \
           daudioplayer.h 
SOURCES += daudioplayer.cpp 
