# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/packages
# Target is a library:  

HEADERS += package.h \
           items.h \
           project.h 
SOURCES += package.cpp \
           items.cpp \
           project.cpp 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib

include(packages_config.pri)

