# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default/sequences
# Target is a library:  

INSTALLS += sequences 
sequences.files += *.png 
sequences.path = /themes/default/sequences/ 
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
