# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/arthury/plugins/tools/atexttoolplugin
# Target is a library:  

QT += xml 
INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          plugin 
TEMPLATE = lib 
HEADERS += texttool.h \
           textconfigurator.h 
SOURCES += texttool.cpp \
           textconfigurator.cpp 

include(../tools.pri)
