# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/lib
# Target is a library:  ktadmin

HEADERS += modulewidgetbase.h \
           package.h \
           modulebuttonbar.h 
SOURCES += modulewidgetbase.cpp \
           package.cpp \
           modulebuttonbar.cpp 
TEMPLATE = lib
CONFIG += staticlib \
warn_on
TARGET = ktadmin

include(../../ktadmin_config.pri)

