# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/interfaces
# Target is a library:  

INSTALLS += ifaceheaders 
ifaceheaders.files += *.h 
ifaceheaders.path = /include/interfaces/ 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += exportinterface.h 
