# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += images \
           lib \
	   dlslib \
           timeline \
           library \
           store \
           opengl \
           qt \
           dialogs \
           exposure \
           core
CONFIG += release \
warn_on
TEMPLATE = subdirs
