/***************************************************************************
 *   Copyright (C) 2004 by Carlos Andres Munoz                             *
 *   carmunoz78@yahoo.com                                                  *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#include "cur/brush.xpm"
#include "cur/circle.xpm"
#include "cur/contour.xpm"
#include "cur/dropper.xpm"
#include "cur/eraser.xpm"
#include "cur/hand.xpm"
#include "cur/magnifying.xpm"
#include "cur/nodes.xpm"
#include "cur/paint.xpm"
#include "cur/pencil.xpm"
#include "cur/pen.xpm"
#include "cur/select.xpm"
#include "cur/slicer.xpm"
#include "cur/square.xpm"
#include "cur/unpaint.xpm"
#include "ico/arrowdown.xpm"
#include "ico/arrowup.xpm"
#include "ico/bezier.xpm"
#include "ico/brush.xpm"
#include "ico/close.xpm"
#include "ico/contour.xpm"
#include "ico/copy.xpm"
#include "ico/cut.xpm"
#include "ico/disable.xpm"
#include "ico/dropper.xpm"
#include "ico/ellipse.xpm"
#include "ico/enable.xpm"
#include "ico/eraser.xpm"
#include "ico/export.xpm"
#include "ico/fillcolor.xpm"
#include "ico/fill.xpm"
#include "ico/fit.xpm"
#include "ico/frame-.xpm"
#include "ico/frame+.xpm"
#include "ico/front_back_grid.xpm"
#include "ico/hand.xpm"
#include "ico/import.xpm"
#include "ico/kilit_pic.xpm"
#include "ico/layer_pic.xpm"
#include "ico/layer-.xpm"
#include "ico/layer+.xpm"
#include "ico/line.xpm"
#include "ico/lock.xpm"
#include "ico/magnifying.xpm"
#include "ico/minussign.xpm"
#include "ico/new.xpm"
#include "ico/nodes.xpm"
#include "ico/open.xpm"
#include "ico/outline_pic.xpm"
#include "ico/paste.xpm"
#include "ico/pencil.xpm"
#include "ico/perspective.xpm"
#include "ico/plussign.xpm"
#include "ico/redo.xpm"
#include "ico/removefill.xpm"
#include "ico/save.xpm"
#include "ico/selection.xpm"
#include "ico/show_hide_all_layers.xpm"
#include "ico/slicer.xpm"
#include "ico/square.xpm"
#include "ico/undo.xpm"
#include "ico/written_pic.xpm"
#include "ico/zoom-in.xpm"
#include "ico/zoom-out.xpm"
#include "ico/grid12.xpm"
#include "ico/grid16.xpm"
#include "ico/subgrid.xpm"
#include "ico/nogrid.xpm"
#include "ico/insert_cg.xpm"
#include "ico/addfolder.xpm"
#include "ico/folder_icon.xpm"
#include "ico/redhat-graphics.xpm"
#include "ico/sound_widget.xpm"
#include "ico/ani_mode.xpm"
#include "ico/bring_to_front.xpm"
#include "ico/brushes.xpm"
#include "ico/camera_preview.xpm"
#include "ico/color_palette.xpm"
#include "ico/drawing_area.xpm"
#include "ico/exposure_sheet.xpm"
#include "ico/group.xpm"
#include "ico/illus_mode.xpm"
#include "ico/library.xpm"
#include "ico/light_table.xpm"
#include "ico/ntsc.xpm"
#include "ico/one_backward.xpm"
#include "ico/one_forward.xpm"
#include "ico/properties.xpm"
#include "ico/render.xpm"
#include "ico/scenes.xpm"
#include "ico/send_to_back.xpm"
#include "ico/side_camera.xpm"
#include "ico/time_line.xpm"
#include "ico/tools.xpm"
#include "ico/top_camera.xpm"
#include "ico/ungroup.xpm"
#include "ico/no_previous.xpm"
#include "ico/previous.xpm"
#include "ico/previous2.xpm"
#include "ico/previous3.xpm"
#include "ico/no_next.xpm"
#include "ico/next.xpm"
#include "ico/next2.xpm"
#include "ico/next3.xpm"
#include "ico/align_l.xpm"
#include "ico/align_r.xpm"
#include "ico/align_t.xpm"
#include "ico/align_b.xpm"
#include "ico/align_cv.xpm"
#include "ico/align_ch.xpm"
#include "ima/background.xpm"
#include "ima/splash.xpm"
