# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default/icons
# Target is a library:  

INSTALLS += icons 
icons.files += *.png 
icons.path = /themes/default/icons 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
