# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dlib
# Target is a subdirs project 

SUBDIRS += dcore \
           dsound \
           dgui \
           plugins 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
