# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/lib
# Target is a library:  ktserver

HEADERS += sproject.h
SOURCES += sproject.cpp 
TARGET = ktserver
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
include(lib_config.pri)
