# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/contourselection
# Target is a library:  

QT += xml 
INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
include(../tools.pri)
CONFIG += release \
          warn_on \
          plugin 
TEMPLATE = lib 
HEADERS += contourselection.h \
           controlnode.h 
SOURCES += contourselection.cpp \
           controlnode.cpp 
