# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export/smilexportplugin
# Target is a library:  

INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
include(../export_config.pri)
MOC_DIR = .moc 
UI_DIR = .ui 
OBJECTS_DIR = .obj 
CONFIG += plugin 
TEMPLATE = lib 
HEADERS += smilexportplugin.h 
SOURCES += smilexportplugin.cpp
include(../../../../ktconfig.pri)