# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a library:  ../bin/dsoap

QT = network 
TARGET = ../bin/dsoap 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += dsoap.h 
SOURCES += dsoap.cpp 

QT += network xml core
