# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/help
# Target is a library:  

INSTALLS += help 
help.files += help 
help.path = /data/ 
KDEV_QTVER = 4 
include(../components_config.pri)

CONFIG += static
TEMPLATE = lib 
HEADERS += kthelpwidget.h \
           kthelpbrowser.h 
SOURCES += kthelpwidget.cpp \
           kthelpbrowser.cpp 

