# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qdxs

HEADERS += dsoap.h \
           ddxs.h 
SOURCES += main.cpp \
           dsoap.cpp \
           ddxs.cpp 
QT += xml network gui 
KDEV_QTVER = 4 
MOC_DIR = .moc 
UI_DIR = .ui 
OBJECTS_DIR = .obj 
TARGET = ../bin/qdxs 
CONFIG += release \
          warn_on 
TEMPLATE = app 
