# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/pen
# Target is a library:  

KDEV_QTVER = 4 

include(../components_config.pri)

CONFIG += static

TEMPLATE = lib 
HEADERS += ktpenwidget.h 
SOURCES += ktpenwidget.cpp 
