######################################################################
# Automatically generated by qmake (2.00a) Fri Jan 20 09:20:03 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
