# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/arthury/plugins/tools/ageometrictool
# Target is a library:  

INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
CONFIG += plugin 
include(../../../../ktconfig.pri)

TEMPLATE = lib 
HEADERS += geometrictool.h 
SOURCES += geometrictool.cpp 

include(../tools_config.pri)

