# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += themes \
           lib \
           dlslib \
           store \
           dialogs \
           components \
           modules \
           ktoonstyle \ 
           core
QT += qt3support
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
