# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/arthury/interfaces
# Target is a library:  

HEADERS += adrawingtoolinterface.h \
           afilterinterface.h 
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
