# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./slplib
# Target is a library:  

HEADERS += slpparser.h \
           slpentry.h \
           slpmanager.h \
           slpgenerator.h 
SOURCES += slpparser.cpp \
           slpentry.cpp \
           slpmanager.cpp \
           slpgenerator.cpp 
QT += xml
MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
