# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/scenes
# Target is a library:  

QT += qt3support xml
INCLUDEPATH += ../../../src/lib 
MOC_DIR = .moc 
UI_DIR = .ui 
OBJECTS_DIR = .obj 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += ktsceneslist.h \
           ktsceneswidget.h 
SOURCES += ktsceneslist.cpp \
           ktsceneswidget.cpp 
