# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

QT += xml
SUBDIRS += slplib \
	   src
TEMPLATE=subdirs
