# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/packages
# Target is a library:  

HEADERS += adduser.h  \
connect.h \
ackparser.h
SOURCES += adduser.cpp  \
connect.cpp \
ackparser.cpp
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib

include(packages_config.pri)

