# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/timeline
# Target is a library:  

HEADERS += kttimeline.h \
           ktlayermanager.h \
           kttlruler.h \
           ktframestable.h 
SOURCES += kttimeline.cpp \
           ktlayermanager.cpp \
           kttlruler.cpp \
           ktframestable.cpp 

CONFIG += static

TEMPLATE = lib

include(../components_config.pri)
