# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/projects
# Target is a library:  

HEADERS += modulewidget.h \
           form.h
SOURCES += modulewidget.cpp \
           form.cpp
TEMPLATE = lib
CONFIG += staticlib \
warn_on
include(../modules_config.pri)
