# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/arthury/plugins/filters
# Target is a subdirs project 

SUBDIRS += atransformfilter 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
