# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

DEFINES = $(KTDEFINES) 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += src 

include ( "config.ktoon" )

