# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dlib/plugins
# Target is a subdirs project 

SUBDIRS += dgstengine 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
