# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default/images
# Target is a library:  

INSTALLS += images 
images.files += *.png 
images.path = /themes/default/images 
CONFIG += release \
warn_on 
TEMPLATE = subdirs
