# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/htscape

HEADERS += hsmainwindow.h 
SOURCES += main.cpp \
           hsmainwindow.cpp 
TARGET=../bin/htscape
