# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/ellipse
# Target is a library:  

QT += xml 
INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          plugin 
TEMPLATE = lib 
HEADERS += node.h \
           ellipse.h 
SOURCES += node.cpp \
           ellipse.cpp 

include(../tools.pri)
