# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools
# Target is a subdirs project 

SUBDIRS += brush \
           select \
           contourselection \
           text \
           geometrictool \
           viewtool \
           filltool \
           erasertool 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
