######################################################################
# Automatically generated by qmake (2.01a) Tue May 18 22:16:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml

# Input
HEADERS += ktwitter.h
SOURCES += ktwitter.cpp main.cpp
TARGET = ktwitter
