# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += themes \
           dlib \
           libktoon \
           store \
	   libbase \
           libktui \
           components \
           shell \
           plugins 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
