# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += images \
           lib \
           timeline \
           library \
           store \
           opengl \
           qt \
           dialogs \
           core \
           exposure 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
