# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

KDEV_QTVER = 4 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += themes \
           dlib \
           libktoon \
           store \
           libktui \
           components \
           shell \
           plugins 
