# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/scenes
# Target is a library:  

KDEV_QTVER = 4 
include(../components_config.pri)
CONFIG += static

TEMPLATE = lib 
HEADERS += ktsceneslist.h \
           ktsceneswidget.h 
SOURCES += ktsceneslist.cpp \
           ktsceneswidget.cpp 
