/***************************************************************************
 *   Copyright (C) 2004 by Carlos Andres Munoz                             *
 *   carmunoz78@yahoo.com                                                  *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
 
#include "images.h"

#include "../cursors/brush.xpm"
#include "../cursors/circle.xpm"
#include "../cursors/contour.xpm"
#include "../cursors/dropper.xpm"
#include "../cursors/eraser.xpm"
#include "../cursors/hand.xpm"
#include "../cursors/magnifying.xpm"
#include "../cursors/nodes.xpm"
#include "../cursors/paint.xpm"
#include "../cursors/pencil.xpm"
#include "../cursors/pen.xpm"
#include "../cursors/select.xpm"
#include "../cursors/slicer.xpm"
#include "../cursors/square.xpm"
#include "../cursors/unpaint.xpm"
#include "../icons/arrowdown.xpm"
#include "../icons/arrowup.xpm"
#include "../icons/bezier.xpm"
#include "../icons/brush.xpm"
#include "../icons/close.xpm"
#include "../icons/contour.xpm"
#include "../icons/copy.xpm"
#include "../icons/cut.xpm"
#include "../icons/disable.xpm"
#include "../icons/dropper.xpm"
#include "../icons/ellipse.xpm"
#include "../icons/enable.xpm"
#include "../icons/eraser.xpm"
#include "../icons/export.xpm"
#include "../icons/fillcolor.xpm"
#include "../icons/fill.xpm"
#include "../icons/fit.xpm"
#include "../icons/frame-.xpm"
#include "../icons/frame+.xpm"
#include "../icons/front_back_grid.xpm"
#include "../icons/hand.xpm"
#include "../icons/import.xpm"
#include "../icons/kilit_pic.xpm"
#include "../icons/layer_pic.xpm"
#include "../icons/layer-.xpm"
#include "../icons/layer+.xpm"
#include "../icons/line.xpm"
#include "../icons/lock.xpm"
#include "../icons/magnifying.xpm"
#include "../icons/minussign.xpm"
#include "../icons/new.xpm"
#include "../icons/nodes.xpm"
#include "../icons/open.xpm"
#include "../icons/outline_pic.xpm"
#include "../icons/paste.xpm"
#include "../icons/pencil.xpm"
#include "../icons/perspective.xpm"
#include "../icons/plussign.xpm"
#include "../icons/redo.xpm"
#include "../icons/removefill.xpm"
#include "../icons/save.xpm"
#include "../icons/selection.xpm"
#include "../icons/show_hide_all_layers.xpm"
#include "../icons/slicer.xpm"
#include "../icons/square.xpm"
#include "../icons/undo.xpm"
#include "../icons/written_pic.xpm"
#include "../icons/zoom-in.xpm"
#include "../icons/zoom-out.xpm"
#include "../icons/grid12.xpm"
#include "../icons/grid16.xpm"
#include "../icons/subgrid.xpm"
#include "../icons/nogrid.xpm"
#include "../icons/insert_cg.xpm"
#include "../icons/addfolder.xpm"
#include "../icons/folder_icon.xpm"
#include "../icons/redhat-graphics.xpm"
#include "../icons/sound_widget.xpm"
#include "../icons/ani_mode.xpm"
#include "../icons/bring_to_front.xpm"
#include "../icons/brushes.xpm"
#include "../icons/camera_preview.xpm"
#include "../icons/color_palette.xpm"
#include "../icons/drawing_area.xpm"
#include "../icons/exposure_sheet.xpm"
#include "../icons/group.xpm"
#include "../icons/illus_mode.xpm"
#include "../icons/library.xpm"
#include "../icons/light_table.xpm"
#include "../icons/ntsc.xpm"
#include "../icons/one_backward.xpm"
#include "../icons/one_forward.xpm"
#include "../icons/properties.xpm"
#include "../icons/render.xpm"
#include "../icons/scenes.xpm"
#include "../icons/send_to_back.xpm"
#include "../icons/side_camera.xpm"
#include "../icons/time_line.xpm"
#include "../icons/tools.xpm"
#include "../icons/top_camera.xpm"
#include "../icons/ungroup.xpm"
#include "../icons/no_previous.xpm"
#include "../icons/previous.xpm"
#include "../icons/previous2.xpm"
#include "../icons/previous3.xpm"
#include "../icons/no_next.xpm"
#include "../icons/next.xpm"
#include "../icons/next2.xpm"
#include "../icons/next3.xpm"
#include "../icons/align_l.xpm"
#include "../icons/align_r.xpm"
#include "../icons/align_t.xpm"
#include "../icons/align_b.xpm"
#include "../icons/align_cv.xpm"
#include "../icons/align_ch.xpm"

#include "background.xpm"

