# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components
# Target is a subdirs project 

SUBDIRS += brushes \
           scenes \
           colorpalette \
           library \
           timeline \
           exposure \
           export \
           import \
           gceditor \
           help \
           kinas 
CONFIG += release \
warn_on
TEMPLATE = subdirs
QT += qt3support xml opengl
