# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/svnlogparser

QT += xml 
KDEV_QTVER = 4 
TARGETDEPS += ../slplib/libslplib.a 
LIBS += ../slplib/libslplib.a \
        -lsvn_client-1 
INCLUDEPATH += ../slplib 
TARGET = ../bin/svnlogparser 
CONFIG += release \
          warn_on 
TEMPLATE = app 
SOURCES += main.cpp 
