# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/svnlogparser

QT += xml
TARGETDEPS += ../slplib/libslplib.a 
LIBS += ../slplib/libslplib.a 
INCLUDEPATH += ../slplib 
TARGET = ../bin/svnlogparser 
CONFIG += release \
          warn_on 
TEMPLATE = app 
SOURCES += main.cpp 
