# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/modules/arthury/plugins/tools
# Target is a subdirs project 

SUBDIRS += agenericbrush \
           ageometrictool \
           ashapebrushplugin \
           aselectiontool \
           atexttoolplugin \
           aerasertool \
           afilltool 
CONFIG += release \
warn_on
TEMPLATE = subdirs
