# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/exposure
# Target is an application:  

HEADERS += exposuresheet.h 
