# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += kom
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 

include(qonf.pri)

