# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/exposure
# Target is a library:  

HEADERS += ktexposuresheet.h \
           ktexposuretable.h \
           ktscenetabwidget.h
SOURCES += ktexposuresheet.cpp \
           ktexposuretable.cpp \
           ktscenetabwidget.cpp

include(../components_config.pri)

CONFIG += static
TEMPLATE = lib


