# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dlib
# Target is a subdirs project 

SUBDIRS += dcore dsound dgui plugins
CONFIG += release \
warn_on
TEMPLATE = subdirs

